config/routes.rb
DSO::Application.routes.draw do
  
  root :to => 'clips#home'
  
  scope "/admin" do
    root :to => redirect('/admin/clips') #just to provide a default action. may be changed.
    match 'clips/new' => 'clips#new'
    match 'clips/:id' => 'clips#read'
    match 'clips/:id/reset' => 'clips#reset'
    match 'clips/transcript/:id' => 'clips#transcript'
    resources :clips
  end

  match "transcribe" => 'clips#show'
  match 'clips/:id/update' => 'clips#update'
  resources :clips

  match "/success/:id" => 'clips#home'
  
  
end

app/models/clip.rb
class Clip < ActiveRecord::Base
  has_many :segments
  belongs_to :movie
  
  def destroy_segments
    self.segments.each do |seg| seg.destroy end
  end

  #security concern in this process
  def store_segments(clipjson)
    cliphash = ActiveSupport::JSON.decode(clipjson) 
    clip_id = cliphash['clip_id']
    cliphash['segs'].each do |seg|
      Segment.create({ :clip_id => self.id,
                       :speaker => seg['speaker'],
                       :text => seg['text'],
                       :timestart => seg['timestart'],
                       :timeend => seg['timeend']
                     })
      end
      self.worker_time = cliphash['time_elapsed']  
    self.status = true
    return self.save
  end


  def self.get_random_unfinished
    pool = find_all_by_status(false);
    pool.sample
  end
  
  #display the files which do not yet have clips initialized.
  def self.get_fresh_videos
    dir_contents = Dir.entries("public/videos");   
    #build a hashset of the clip's urls                   O(n)
    filenames = Hash.new
    Clip.all.each do |c|
      filenames[c.url] = nil
    end
    #for each dir_content elem, ask is it in the hashset?    O(n)
    urls = Array.new
    dir_contents.each do |file|
         is_dotdot = file == '.' || file == '..'
         #is video = (some regex magic?)
         urls << file unless filenames.has_key?(file) || is_dotdot #&& is video
    end
    return urls
  end
 
  # CSV format
  # speaker,start,end,text
  def get_transcript()
    transcript = ""
    delimiter = "\t"
    self.segments.each do |seg|
      transcript << seg.speaker + delimiter
      transcript << Clip.format_time(seg.timestart) + delimiter
      transcript << Clip.format_time(seg.timeend) + delimiter
      transcript << seg.text + "\n"
    end
    return transcript
  end
  
  #take in a time in seconds
  #convert it to HH:MM:SS.mmm
  # examples: 21392
  # 21392 -> 5,,32
  def self.format_time(seconds)
      hours = seconds/60/60
      minutes = seconds/60 % 60
      seconds = seconds % 60
      time = Time.new(2000, 1, 1, hours, minutes, seconds)
      str = time.strftime("%k:%M:%S.%L")
  end
 
end

app/controllers/clips_controller.rb
load 'youtube.rb'

class ClipsController < ApplicationController
  def home
    @pageName = "Choose a Role"
    @pageDescription = ""
    unless params[:id].nil?
      flash[:notice] = "Transcript was successfully saved!"
    end
  end

  #GET /clips/admin/:id
  # this is how the admin gets more info about the clip
  def read
    @clip = Clip.find(params[:id])
    @pageName = "Video Info"
    @pageDescription = "for #{@clip.url}"
    # if @clip.nil? // what to do here?  
  end
  

  # GET /transcribe
  def show
    @clip = Clip.get_random_unfinished
    if @clip.nil?
      redirect_to :action => 'home', :notice => "No more videos to transcribe"  #flash notices?
    else 
      #@youtubeURL = Youtube.grab_single_url_filename(@clip.url)[:url] unless @clip.localFile THIS IS HOW TO GET THE YOUTUBE DOWNLOAD LINK
      render :show, :layout => 'transcribe'
    end
end

  def new
   @pageName = "Add to Queue"
   @pageDescription = "Queue the transcription of a new video."
   @clip = Clip.new 
   @urls = Clip.get_fresh_videos
  end
  
  def index
   @pageName = "The Admin's Home"
   @pageDescription = "A place to see the status of all the videos."
   @clips = Clip.all
  end

#is this supposed to be here or in the model? what goes in the model?
  def create
    params[:url] = params[:remoteurl] unless params[:remoteurl].nil?
    @clip = Clip.new(params[:clip])
    # path = File.expand_path("public/videos/" + @clip.url)
    # file = RVideo::Inspector.new(:file => path)
    ###### the lines above and below this  were commented to enable heroku use. 
    # @clip.length = file.duration
    
    @clip.localFile = !@clip.url.include?('/')
    @clip.status = false
    @clip.timestart = 0

    respond_to do |format|
    if @clip.save
      format.html  { redirect_to( :action => "index",
                    :notice => 'Clip was successfully created.') }
      format.json  { render :json => @clip,
                    :status => :created, :location => @clip }
    else
      format.html  { render :action => "new" }
      format.json  { render :json => @clip.errors,
                    :status => :unprocessable_entity }
    end end
  end  


  # this is the function called when the user presses "save transcript"
  def update
    clip = Clip.find(params[:id])
    if clip.store_segments(params[:JSON])
      send_data "OK"
    else
      send_data "NO"
    end
  end

  # destroys clip,
  # displays index view
  def destroy
    clip = Clip.find(params[:id])
    clip.destroy_segments
    clip.destroy
    File.delete("public/videos/#{clip.url}")
    redirect_to :action => 'index'
  end

  
  #this is to delete the table entry without deleting the file
  #concern: not DRY. how to refactor with the destroy function?
  def reset
    clip = Clip.find(params[:id])
    clip.destroy_segments
    clip.destroy
    redirect_to :action => 'index'
  end
  
  #GET /admin/clips/transcript/:id
  def transcript
    clip = Clip.find(params[:id])
    if clip.nil? || clip.status == false
      render :nothing => true
    else
      transcript = clip.get_transcript
      send_data transcript, :filename => "#{clip.url}-CSV.txt", :type => "text/plain"
    end
  end
      
end

app/helpers/clips_helper.rb
module ClipsHelper
end

app/views/clips/home.html.erb
<style>
<% containerWidth = 750
   boxSide = containerWidth/2 - 10 %>
#container {
margin-left: auto; margin-right: auto;
width:<%= "#{containerWidth}px"  %>;
}
.bigfont { font-size:24pt; }
.left { float:left; }
.right {float:right; }
.box { width:<%= "#{boxSide}px" %>; height:<%= "#{boxSide}px" %>   }
</style>
<div id="container">
<% unless flash[:notice].nil? %>
  <div class="alert-message success"><%= flash[:notice] %></div>
<%end%>
<div class="bigfont left box"><%= link_to "Admin", clips_path %></div>
<div class="bigfont right box"><%= link_to "Transcriber", :controller => "clips", :action => "show" %></div>
</div>

app/views/clips/index.html.erb
<div class="span13">
<h1>Listing of Queued Videos</h1>
<table>
<tr>
<th>File name/URL</th>
<th>Local File?</th>
<th>Status</th>
<th></th>
<th></th>
</tr>

<% @clips.each do |clip| %>
<tr>
<td><%= link_to clip.url, :id => clip.id, :controller => "clips", :action => "read" %></td>
<td><%= clip.localFile %></td>
<td><%= "Pending" if !clip.status %>
    <%= "Done!"   if clip.status %></td>
<td> <%= link_to "Reset", :id => clip.id, :controller => "clips", :action => "reset" %> </td>
<td> <%= button_to "Delete", clip, :confirm => "Are you sure? This will also delete the file permanently.", :method => "delete" %> </td>
</tr>
<% end %>
</table>
<p> <%= link_to "Add a file", new_clip_path %> to start a new transcription project.</p>
</div>

app/views/clips/new.html.erb
<style>
label { float:none }/** Overriding bootstrap to make it look normal */
</style>


<div class="span10">
<h2>Choose a file to initialize</h2>
<% if @urls.size == 0 %>
  There are no new video files in the public/videos folder. Please add one and refresh.
<% else %>
<%= form_for @clip do |f| %>
  <ul>
    <% @urls.each do |filename| %>
      <li>
      <%= f.radio_button :url, filename %>
      <%= f.label :url, filename %>
      </li>
    <% end %>
  </ul>
  <%= f.submit %>
  <% end end %>
<%= form_for @clip do |f| %>
  Or, enter the URL to the media file:
  <%= f.text_field :url %><br />
  <%= f.submit %>
<% end %>

</div>

app/views/clips/read.html.erb
<div class="span 13">

<% if @clip.status %>
<% lastspeaker = "" %>
  <h2> Transcript </h2>
  <table>
  <% @clip.segments.each do |seg| %>
    <tr>
      <td>
        <%= seg.speaker if !seg.speaker.eql?(lastspeaker) %>
      </td>
      <td>
        <%= "#{seg.timestart}s - #{seg.timeend}s" %>
      </td>
      <td>
        <%= seg.text %>
      </td>
    </tr>
  <%    lastspeaker = seg.speaker
      end %>
  </table>
  <h2>Time taken to transcribe: </h2>
  <p><%= "#{@clip.worker_time} seconds" %></p>
  <p><%= link_to "Download the Transcript", :controller => "clips", :action => "transcript", :id => @clip.id %></p>
<% else %> 

<h2>Status: Pending</h2>

<% end %>
</div>

app/views/clips/show.html.erb
<div id='clipid' style="display:none"><%=  @clip.id %></div>
		<!-- top container (logo, welcome) -->
		<!--<div id="topContainer">
			<div id="logoArea"></div>
			<div id="welcomeMsg">hello, Adi!</div> 
			<div id="logoutMsg"> Logout </div>
		</div>-->
		<!-- end top container -->
		
		<!-- main container -->
		<div id="mainContainer">			
			
			<!-- left content area -->
			<div id="leftContentArea">
				<div id="videoPanel">
					<a  
            href="<%= if @clip.localFile 
                        video_path(@clip.url)
                       else @clip.url
                       end%>"
						 id="player"> 
					</a>							
				</div>				
				<div id="transcriptionPanel">
					<div class="wrapper">
						<table cellspacing="0" cellpadding="0">
							<tbody>
							<tr class="segment active">
								<td class="seg_left">
									<!--<input class="timestamp active" type="text" value="00:00" disabled="" />-->
									<div class="timestamp active">
										<div class="start"></div>
										<div class="separator"> - </div>
										<div class="end"></div>	
									</div>
									<p class="speaker ui-corner-top ui-corner-bottom"> </p>
								</td>
								<td class="seg_right">
									<textarea class="active txt">Start typing here ... </textarea>
									<div class="reviewWrapper ui-corner-top ui-corner-bottom" style="float:right;display:none">
										<button class="rEdit ui-icon ui-icon-pencil"> </button>
										<button class="rSave ui-icon ui-icon-disk" style="display:none"> </button>
										<button class="rDel ui-icon ui-icon-trash"> </button>
									</div>
								</td>
							</tr>
							</tbody>
						</table>						
					</div>
					<div id="buttonArea">
						<button id="review" class="quickAccess" accesskey="Ctrl+Alt+R"> </button>
						<button id="done" class="quickAccess" style="display:none"> </button>
						<button id="export" class="quickAccess" accesskey="Ctrl+Alt+E" > </button><!-- Want to make this a submit action which POSTs a JSON -->
					</div>
				</div>				
			</div>
			<!-- end left content area -->
			
			<!-- right content area -->

			<div id="rightContentArea">
			<div class="wrapper ui-accordion ui-widget ui-helper-reset">
				<div class="title ui-accordion-header ui-helper-reset ui-state-active ui-corner-top">
					<span> Keyboard Commands </span>
					<span class="ui-icon ui-icon-triangle-1-s act"/>					
					<!--<img src="images/down-arrow.png" class="act" />-->
				</div>
				<div class="content ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom">
					<table id="keyboardShortcuts">
						<thead>
							<tr>
								<th>Command</th>
								<th>Shortcut</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td><div>Play/Pause video</div></td>
								<td><div>Ctrl+Space</div></td>
							</tr>
							<tr>
								<td><div>Forward 10 sec</div></td>
								<td><div>Ctrl+Alt+&rarr;</div></td>
							</tr>
							<tr>
								<td><div>Backward 10 sec</div></td>
								<td><div>Ctrl+Alt+&larr;</div></td>
							</tr>
							<tr>
								<td><div>Move to previous segment</div></td>
								<td><div>Ctrl+Alt+&uarr;</div></td>
							</tr>
							<tr>
								<td><div>Move to next segment</div></td>
								<td><div>Ctrl+Alt+&darr;</div></td>
							</tr>
							<tr>
								<td><div>Toggle speaker</div></td>
								<td><div>Alt+S</div></td>
							</tr>
							<tr>
								<td><div>Add new speaker</div></td>
								<td><div>Ctrl+Alt+S</div></td>
							</tr>
							<tr>
								<td><div>OR Add new speaker (one higher than the current number)</div></td>
								<td><div>@+S+spacebar</div></td>
							</tr>
							<tr>
								<td><div>OR Add new speaker (with a specified number)</div></td>
								<td><div>@+S+x, where x is an integer</div></td>
							</tr>
						</tbody>
					</table>
				</div>
				<div class="title ui-accordion-header ui-helper-reset ui-state-active ui-corner-top">
					<span>Speaker Information</span>
					<span class="ui-icon ui-icon-triangle-1-s act"/>
				</div>
				<div class="content ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom">

					<div id="spValidationMsg" class="ui-corner-all" style="display:none;">
						<p>
							<span class="ui-icon"></span>
						</p>
					</div>
					<table id="speakerInfo">
						<thead>
							<tr>
								<th>#</th>
								<th>Color</th>
								<th>Name</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
					<!--<button id="newSpAdd" accesskey="Ctrl+Alt+S"> </button>-->
				</div>
				<div class="title ui-accordion-header ui-helper-reset ui-state-active ui-corner-top">
					<span> Video Information </span>
					<span class="ui-icon ui-icon-triangle-1-s act"/>
				</div>
				<div class="content content ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom" id="videoInfo">
					<p><span class="label">Title</span><br /><%= @clip.url %></p>
				</div>								
											
			</div>

			<!-- end right content area -->
		
		</div>
		<!-- end main container -->